name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: Slimefun5/workflows/.github/workflows/ci.yml@main
      
      - name: Upload built JARs
        uses: actions/upload-artifact@v4
        with:
          name: serenity-build-${{ github.sha }}
          path: build/libs/*.jar
          retention-days: 30
